

import '../../../../constants/app_constants.dart';
import '../../lecture/lecture_modele.dart';

/*
0 -> "Fè'éfè'é"
1 -> "Douala"
2 -> "Bangangté"
3 -> "Yambassa"
4 ->  "Étón"
*/
int indexNufi = 0,indexDouala = 1, indexBangante = 2, indexYambassa = 3, indexEton = 4;
var listeLectureAnimaux = [
  LectureModele(text: "abeille", imageUrl: "${imageUrlBaseAnimal}l_abeille.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}abeille_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "chevre", imageUrl: "${imageUrlBaseAnimal}la_chevre.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}chevre_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "aigle", imageUrl: "${imageUrlBaseAnimal}l_aigle.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}aigle_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "mouche", imageUrl: "${imageUrlBaseAnimal}la_mouche.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}mouche_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "antilope", imageUrl: "${imageUrlBaseAnimal}l_antilope.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}antilope_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "panthere", imageUrl: "${imageUrlBaseAnimal}la_panthere.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}panthere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "perdrix", imageUrl: "${imageUrlBaseAnimal}la_perdrix.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}perdrix_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "poule", imageUrl: "${imageUrlBaseAnimal}la_poule.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}poule_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "queue", imageUrl: "${imageUrlBaseAnimal}la_queue.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}queue_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "souris", imageUrl: "${imageUrlBaseAnimal}la_souris.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}souris_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "tortue", imageUrl: "${imageUrlBaseAnimal}la_tortue.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}tortue_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "vache", imageUrl: "${imageUrlBaseAnimal}la_vache.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}vache_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "vipere", imageUrl: "${imageUrlBaseAnimal}la_vipere.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}vipere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "belier", imageUrl: "${imageUrlBaseAnimal}le_belier.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}belier_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),

  LectureModele(text: "boeuf", imageUrl: "${imageUrlBaseAnimal}le_boeuf.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}boeuf_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "buffle", imageUrl: "${imageUrlBaseAnimal}le_buffle.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}buffle_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cameleon", imageUrl: "${imageUrlBaseAnimal}le_cameleon.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}cameleon_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cancrelat", imageUrl: "${imageUrlBaseAnimal}le_cancrelat.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}cancrelat_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cheval", imageUrl: "${imageUrlBaseAnimal}le_cheval.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}cheval_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "chien", imageUrl: "${imageUrlBaseAnimal}le_chien.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}chien_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "coq", imageUrl: "${imageUrlBaseAnimal}le_coq.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}coq_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "hibou", imageUrl: "${imageUrlBaseAnimal}le_hibou.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}hibou_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "elephant", imageUrl: "${imageUrlBaseAnimal}l_elephant.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}elephant_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "lievre", imageUrl: "${imageUrlBaseAnimal}le_lievre.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}lievre_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "lion", imageUrl: "${imageUrlBaseAnimal}le_lion.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}lion_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "loup", imageUrl: "${imageUrlBaseAnimal}le_loup.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}loup_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "mouton", imageUrl: "${imageUrlBaseAnimal}le_mouton.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}mouton_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "papillon", imageUrl: "${imageUrlBaseAnimal}le_papillon.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}papillon_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  
  LectureModele(text: "poussin", imageUrl: "${imageUrlBaseAnimal}le_poussin.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}poussin_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "rat", imageUrl: "${imageUrlBaseAnimal}le_rat.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}rat_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "renard", imageUrl: "${imageUrlBaseAnimal}le_renard.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}renard_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "serpent", imageUrl: "${imageUrlBaseAnimal}le_serpent.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}serpent_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "singe", imageUrl: "${imageUrlBaseAnimal}le_singe.jpg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}singe_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "hippopotame", imageUrl: "${imageUrlBaseAnimal}l_hippopotame.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}hippopotame_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "oiseau", imageUrl: "${imageUrlBaseAnimal}l_oiseau.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}oiseau_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "oeuf", imageUrl: "${imageUrlBaseAnimal}oeuf.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}oeuf_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  
    LectureModele(text: "corne", imageUrl: "${imageUrlBaseAnimal}la_corne.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}corne_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    LectureModele(text: "peau", imageUrl: "${imageUrlBaseAnimal}la_peau.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}peau_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    LectureModele(text: "poil", imageUrl: "${imageUrlBaseAnimal}le_poil.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}poil_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    LectureModele(text: "ecaille", imageUrl: "${imageUrlBaseAnimal}une_ecaille.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}ecaille_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    
    LectureModele(text: "fourmi", imageUrl: "${imageUrlBaseAnimal}une_fourmi.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}fourmi_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    
    LectureModele(text: "girafe", imageUrl: "${imageUrlBaseAnimal}une_girafe.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}girafe_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    
    LectureModele(text: "patte", imageUrl: "${imageUrlBaseAnimal}une_patte.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}patte_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    
    LectureModele(text: "plume", imageUrl: "${imageUrlBaseAnimal}une_plume.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}plume_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    
    LectureModele(text: "poisson", imageUrl: "${imageUrlBaseAnimal}un_poisson.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}poisson_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
    
    LectureModele(text: "zebre", imageUrl: "${imageUrlBaseAnimal}un_zebre.jpeg",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseAnimal}zebre_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
]
;
