

import '../../../../constants/app_constants.dart';
import '../../lecture/lecture_modele.dart';

/*
0 -> "Fè'éfè'é"
1 -> "Douala"
2 -> "Bangangté"
3 -> "Yambassa"
4 ->  "Étón"
*/
int indexNufi = 0,indexDouala = 1, indexBangante = 2, indexYambassa = 3, indexEton = 4;
var listeLectureNombre = [
  LectureModele(text: "zero", imageUrl: "${imageUrlBaseCompter}0.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}0_nufi.ogg",languePrisEnCharge[indexDouala]:"${audioUrlBaseCompter}0_dla.ogg",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}0_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}0_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "un", imageUrl: "${imageUrlBaseCompter}1.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}1_nufi.ogg",languePrisEnCharge[indexDouala]:"${audioUrlBaseCompter}1_dla.ogg",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}1_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}1_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "deux", imageUrl: "${imageUrlBaseCompter}2.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}2_nufi.ogg",languePrisEnCharge[indexDouala]:"${audioUrlBaseCompter}2_dla.ogg",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}2_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}2_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "trois", imageUrl: "${imageUrlBaseCompter}3.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}3_nufi.ogg",languePrisEnCharge[indexDouala]:"${audioUrlBaseCompter}3_dla.ogg",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}3_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}3_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quatre", imageUrl: "${imageUrlBaseCompter}4.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}4_nufi.ogg",languePrisEnCharge[indexDouala]:"${audioUrlBaseCompter}4_dla.ogg",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}4_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}4_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cinq", imageUrl: "${imageUrlBaseCompter}5.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}5_nufi.ogg",languePrisEnCharge[indexDouala]:"${audioUrlBaseCompter}5_dla.ogg",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}5_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}5_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "six", imageUrl: "${imageUrlBaseCompter}6.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}6_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}6_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}6_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "sept", imageUrl: "${imageUrlBaseCompter}7.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}7_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}7_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}7_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "huit", imageUrl: "${imageUrlBaseCompter}8.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}8_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}8_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}8_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "neuf", imageUrl: "${imageUrlBaseCompter}9.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}9_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}9_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}9_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "dix", imageUrl: "${imageUrlBaseCompter}10.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}10_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}10_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}10_yambas.ogg",languePrisEnCharge[indexEton]:""}),

  LectureModele(text: "onze", imageUrl: "${imageUrlBaseCompter}11.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}11_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}11_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}11_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "douze", imageUrl: "${imageUrlBaseCompter}12.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}12_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}12_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}12_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "treize", imageUrl: "${imageUrlBaseCompter}13.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}13_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}13_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}13_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quatoze", imageUrl: "${imageUrlBaseCompter}14.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}14_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}14_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}14_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quinze", imageUrl: "${imageUrlBaseCompter}15.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}15_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}15_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}15_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "seize", imageUrl: "${imageUrlBaseCompter}16.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}16_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}16_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}16_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "dix-sept", imageUrl: "${imageUrlBaseCompter}17.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}17_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}17_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}17_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "dix-huit", imageUrl: "${imageUrlBaseCompter}18.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}18_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}18_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}18_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "dix-neuf", imageUrl: "${imageUrlBaseCompter}19.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}19_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}19_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}19_yambas.ogg",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "vingt", imageUrl: "${imageUrlBaseCompter}20.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}20_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"${audioUrlBaseCompter}20_bgte.ogg",languePrisEnCharge[indexYambassa]:"${audioUrlBaseCompter}20_yambas.ogg",languePrisEnCharge[indexEton]:""}),

  LectureModele(text: "trente", imageUrl: "${imageUrlBaseCompter}30.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}30_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quarante", imageUrl: "${imageUrlBaseCompter}40.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}40_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cinquante", imageUrl: "${imageUrlBaseCompter}50.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}50_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "soixante", imageUrl: "${imageUrlBaseCompter}60.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}60_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "soixante-dix", imageUrl: "${imageUrlBaseCompter}70.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}70_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quatre-vingt", imageUrl: "${imageUrlBaseCompter}80.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}80_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quatre-vingt-dix", imageUrl: "${imageUrlBaseCompter}90.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}90_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cent", imageUrl: "${imageUrlBaseCompter}100.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}100_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "deux-cent", imageUrl: "${imageUrlBaseCompter}200.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}200_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "trois-cent", imageUrl: "${imageUrlBaseCompter}300.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}300_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "quatre-cent", imageUrl: "${imageUrlBaseCompter}400.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}400_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "cinq-cent", imageUrl: "${imageUrlBaseCompter}500.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}500_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "six-cent", imageUrl: "${imageUrlBaseCompter}600.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}600_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "sept-cent", imageUrl: "${imageUrlBaseCompter}700.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}700_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "huit-cent", imageUrl: "${imageUrlBaseCompter}800.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}800_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "neuf-cent", imageUrl: "${imageUrlBaseCompter}900.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}900_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "mille", imageUrl: "${imageUrlBaseCompter}1000.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBaseCompter}1000_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
]
;
