
import 'package:reenamuna/app/modules/lecture/lecture_modele.dart';

var listeLectureNombre = [
  LectureModele(text: "zero", imageUrl: "assets/images/compter/0.png",audioMap: {"Fè'éfè'é":"audios/compter/0-zero.mp3","Douala":"audios/compter/dla_0.mp3"}),
  LectureModele(text: "un", imageUrl: "assets/images/compter/1.png",audioMap: {"Fè'éfè'é":"audios/compter/1-un.mp3","Douala":"audios/compter/dla_1.mp3"}),
  LectureModele(text: "deux", imageUrl: "assets/images/compter/2.png",audioMap: {"Fè'éfè'é":"audios/compter/2-deux.mp3","Douala":"audios/compter/dla_2.mp3"}),
  LectureModele(text: "trois", imageUrl: "assets/images/compter/3.png",audioMap: {"Fè'éfè'é":"audios/compter/3-trois.mp3","Douala":"audios/compter/dla_3.mp3"}),
  LectureModele(text: "quatre", imageUrl: "assets/images/compter/4.png",audioMap: {"Fè'éfè'é":"audios/compter/4-quatre.mp3","Douala":"audios/compter/dla_4.mp3"}),
  LectureModele(text: "cinq", imageUrl: "assets/images/compter/5.png",audioMap: {"Fè'éfè'é":"audios/compter/5-cinq.mp3","Douala":"audios/compter/dla_5.mp3"}),
  LectureModele(text: "six", imageUrl: "assets/images/compter/6.png",audioMap: {"Fè'éfè'é":"audios/compter/6-six.mp3","Douala":"audios/compter/test.ogg"}),
  LectureModele(text: "sept", imageUrl: "assets/images/compter/7.png",audioMap: {"Fè'éfè'é":"audios/compter/7-sept.mp3","Douala":""}),
  LectureModele(text: "huit", imageUrl: "assets/images/compter/8.png",audioMap: {"Fè'éfè'é":"audios/compter/8-huit.mp3","Douala":""}),
  LectureModele(text: "neuf", imageUrl: "assets/images/compter/9.png",audioMap: {"Fè'éfè'é":"audios/compter/9-neuf.mp3","Douala":""}),
  LectureModele(text: "dix", imageUrl: "assets/images/compter/10.png",audioMap: {"Fè'éfè'é":"audios/compter/10-dix.mp3","Douala":""}),

  LectureModele(text: "onze", imageUrl: "assets/images/compter/11.png",audioMap: {"Fè'éfè'é":"audios/compter/11-onze.mp3","Douala":""}),
  LectureModele(text: "douze", imageUrl: "assets/images/compter/12.png",audioMap: {"Fè'éfè'é":"audios/compter/12-douze.mp3","Douala":""}),
  LectureModele(text: "treize", imageUrl: "assets/images/compter/13.png",audioMap: {"Fè'éfè'é":"audios/compter/13-treize.mp3","Douala":""}),
  LectureModele(text: "quatoze", imageUrl: "assets/images/compter/14.png",audioMap: {"Fè'éfè'é":"audios/compter/14-quatoze.mp3","Douala":""}),
  LectureModele(text: "quinze", imageUrl: "assets/images/compter/15.png",audioMap: {"Fè'éfè'é":"audios/compter/15-quinze.mp3","Douala":""}),
  LectureModele(text: "seize", imageUrl: "assets/images/compter/16.png",audioMap: {"Fè'éfè'é":"audios/compter/16-seize.mp3","Douala":""}),
  LectureModele(text: "dix-sept", imageUrl: "assets/images/compter/17.png",audioMap: {"Fè'éfè'é":"audios/compter/17-dix_sept.mp3","Douala":""}),
  LectureModele(text: "dix-huit", imageUrl: "assets/images/compter/18.png",audioMap: {"Fè'éfè'é":"audios/compter/18-dix_huit.mp3","Douala":""}),
  LectureModele(text: "dix-neuf", imageUrl: "assets/images/compter/19.png",audioMap: {"Fè'éfè'é":"audios/compter/19-dix_neuf.mp3","Douala":""}),
  LectureModele(text: "vingt", imageUrl: "assets/images/compter/20.png",audioMap: {"Fè'éfè'é":"audios/compter/20-vingt.mp3","Douala":""}),

  LectureModele(text: "trente", imageUrl: "assets/images/compter/30.png",audioMap: {"Fè'éfè'é":"audios/compter/30-trente.mp3","Douala":""}),
  LectureModele(text: "quarante", imageUrl: "assets/images/compter/40.png",audioMap: {"Fè'éfè'é":"audios/compter/40-quarante.mp3","Douala":""}),
  LectureModele(text: "cinquante", imageUrl: "assets/images/compter/50.png",audioMap: {"Fè'éfè'é":"audios/compter/50-cinquante.mp3","Douala":""}),
  LectureModele(text: "soixante", imageUrl: "assets/images/compter/60.png",audioMap: {"Fè'éfè'é":"audios/compter/60-soixante.mp3","Douala":""}),
  LectureModele(text: "soixante-dix", imageUrl: "assets/images/compter/70.png",audioMap: {"Fè'éfè'é":"audios/compter/70-soixante_dix.mp3","Douala":""}),
  LectureModele(text: "quatre-vingt", imageUrl: "assets/images/compter/80.png",audioMap: {"Fè'éfè'é":"audios/compter/80-quatre_vingt.mp3","Douala":""}),
  LectureModele(text: "quatre-vingt-dix", imageUrl: "assets/images/compter/90.png",audioMap: {"Fè'éfè'é":"audios/compter/90-quatre_vingt_dix.mp3","Douala":""}),
  LectureModele(text: "cent", imageUrl: "assets/images/compter/100.png",audioMap: {"Fè'éfè'é":"audios/compter/100-cent.mp3","Douala":""}),
  LectureModele(text: "deux-cent", imageUrl: "assets/images/compter/200.png",audioMap: {"Fè'éfè'é":"audios/compter/200-deux_cent.mp3","Douala":""}),
  LectureModele(text: "trois-cent", imageUrl: "assets/images/compter/300.png",audioMap: {"Fè'éfè'é":"audios/compter/300-trois_cent.mp3","Douala":""}),
  LectureModele(text: "quatre-cent", imageUrl: "assets/images/compter/400.png",audioMap: {"Fè'éfè'é":"audios/compter/400-quatre_cent.mp3","Douala":""}),
  LectureModele(text: "cinq-vingt", imageUrl: "assets/images/compter/500.png",audioMap: {"Fè'éfè'é":"audios/compter/500-cinq_cent.mp3","Douala":""}),
  LectureModele(text: "six-cent", imageUrl: "assets/images/compter/600.png",audioMap: {"Fè'éfè'é":"audios/compter/600-six_cent.mp3","Douala":""}),
  LectureModele(text: "sept-cent", imageUrl: "assets/images/compter/700.png",audioMap: {"Fè'éfè'é":"audios/compter/700-sept_cent.mp3","Douala":""}),
  LectureModele(text: "huit-cent", imageUrl: "assets/images/compter/800.png",audioMap: {"Fè'éfè'é":"audios/compter/800-huit_cent.mp3","Douala":""}),
  LectureModele(text: "neuf-cent", imageUrl: "assets/images/compter/900.png",audioMap: {"Fè'éfè'é":"audios/compter/900-neuf_cent.mp3","Douala":""}),
  LectureModele(text: "mille", imageUrl: "assets/images/compter/1000.png",audioMap: {"Fè'éfè'é":"audios/compter/1000-mille.mp3","Douala":""}),
];