
import 'package:reenamuna/app/modules/lecture/lecture_modele.dart';

var listeLectureNombre = [
  LectureModele(text: "zero", imageUrl: "assets/images/compter/0.png",audioMap: {"Fè'éfè'é":"audios/compter/0-zero.mp3","Douala":"audios/compter/dla_0.mp3"}),
  LectureModele(text: "un", imageUrl: "assets/images/compter/1.png",audioMap: {"Fè'éfè'é":"audios/compter/1-un.mp3","Douala":"audios/compter/dla_1.mp3"}),
  LectureModele(text: "deux", imageUrl: "assets/images/compter/2.png",audioMap: {"Fè'éfè'é":"audios/compter/2-deux.mp3","Douala":"audios/compter/dla_2.mp3"}),
  LectureModele(text: "trois", imageUrl: "assets/images/compter/3.png",audioMap: {"Fè'éfè'é":"audios/compter/3-trois.mp3","Douala":"audios/compter/dla_3.mp3"}),
  LectureModele(text: "quatre", imageUrl: "assets/images/compter/4.png",audioMap: {"Fè'éfè'é":"audios/compter/4-quatre.mp3","Douala":"audios/compter/dla_4.mp3"}),
  LectureModele(text: "cinq", imageUrl: "assets/images/compter/5.png",audioMap: {"Fè'éfè'é":"audios/compter/5-cinq.mp3","Douala":"audios/compter/dla_5.mp3"}),
  LectureModele(text: "six", imageUrl: "assets/images/compter/6.png",audioMap: {"Fè'éfè'é":"audios/compter/6-six.mp3","Douala":""}),
  LectureModele(text: "sept", imageUrl: "assets/images/compter/7.png",audioMap: {"Fè'éfè'é":"audios/compter/7-sept.mp3","Douala":""}),
  LectureModele(text: "huit", imageUrl: "assets/images/compter/8.png",audioMap: {"Fè'éfè'é":"audios/compter/8-huit.mp3","Douala":""}),
  LectureModele(text: "neuf", imageUrl: "assets/images/compter/9.png",audioMap: {"Fè'éfè'é":"audios/compter/9-neuf.mp3","Douala":""}),
  LectureModele(text: "dix", imageUrl: "assets/images/compter/10.png",audioMap: {"Fè'éfè'é":"audios/compter/10-dix.mp3","Douala":""}),

  LectureModele(text: "onze", imageUrl: "assets/images/compter/11.png",audioMap: {"Fè'éfè'é":"audios/compter/11-onze.mp3","Douala":""}),
  LectureModele(text: "douze", imageUrl: "assets/images/compter/12.png",audioMap: {"Fè'éfè'é":"audios/compter/12-douze.mp3","Douala":""}),
  LectureModele(text: "treize", imageUrl: "assets/images/compter/13.png",audioMap: {"Fè'éfè'é":"audios/compter/13-treize.mp3","Douala":""}),
  LectureModele(text: "quatoze", imageUrl: "assets/images/compter/14.png",audioMap: {"Fè'éfè'é":"audios/compter/14-quatoze.mp3","Douala":""}),
  LectureModele(text: "quinze", imageUrl: "assets/images/compter/15.png",audioMap: {"Fè'éfè'é":"audios/compter/15-quinze.mp3","Douala":""}),
  LectureModele(text: "seize", imageUrl: "assets/images/compter/16.png",audioMap: {"Fè'éfè'é":"audios/compter/16-seize.mp3","Douala":""}),
  LectureModele(text: "dix-sept", imageUrl: "assets/images/compter/17.png",audioMap: {"Fè'éfè'é":"audios/compter/17-dix_sept.mp3","Douala":""}),
  LectureModele(text: "dix-huit", imageUrl: "assets/images/compter/18.png",audioMap: {"Fè'éfè'é":"audios/compter/18-dix_huit.mp3","Douala":""}),
  LectureModele(text: "dix-neuf", imageUrl: "assets/images/compter/19.png",audioMap: {"Fè'éfè'é":"audios/compter/19-dix_neuf.mp3","Douala":""}),
  LectureModele(text: "vingt", imageUrl: "assets/images/compter/20.png",audioMap: {"Fè'éfè'é":"audios/compter/20-vingt.mp3","Douala":""}),

  LectureModele(text: "trente", imageUrl: "assets/images/compter/30.png",audioMap: {"Fè'éfè'é":"audios/compter/30-trente.mp3","Douala":""}),
  LectureModele(text: "quarante", imageUrl: "assets/images/compter/40.png",audioMap: {"Fè'éfè'é":"audios/compter/40-quarante.mp3","Douala":""}),
  LectureModele(text: "cinquante", imageUrl: "assets/images/compter/50.png",audioMap: {"Fè'éfè'é":"audios/compter/50-cinquante.mp3","Douala":""}),
  LectureModele(text: "soixante", imageUrl: "assets/images/compter/60.png",audioMap: {"Fè'éfè'é":"audios/compter/60-soixante.mp3","Douala":""}),
  LectureModele(text: "soixante-dix", imageUrl: "assets/images/compter/70.png",audioMap: {"Fè'éfè'é":"audios/compter/70-soixante_dix.mp3","Douala":""}),
  LectureModele(text: "quatre-vingt", imageUrl: "assets/images/compter/80.png",audioMap: {"Fè'éfè'é":"audios/compter/80-quatre_vingt.mp3","Douala":""}),
  LectureModele(text: "quatre-vingt-dix", imageUrl: "assets/images/compter/90.png",audioMap: {"Fè'éfè'é":"audios/compter/90-quatre_vingt_dix.mp3","Douala":""}),
  LectureModele(text: "cent", imageUrl: "assets/images/compter/100.png",audioMap: {"Fè'éfè'é":"audios/compter/100-cent.mp3","Douala":""}),
  LectureModele(text: "deux-cent", imageUrl: "assets/images/compter/200.png",audioMap: {"Fè'éfè'é":"audios/compter/200-deux_cent.mp3","Douala":""}),
  LectureModele(text: "trois-cent", imageUrl: "assets/images/compter/300.png",audioMap: {"Fè'éfè'é":"audios/compter/300-trois_cent.mp3","Douala":""}),
  LectureModele(text: "quatre-cent", imageUrl: "assets/images/compter/400.png",audioMap: {"Fè'éfè'é":"audios/compter/400-quatre_cent.mp3","Douala":""}),
  LectureModele(text: "cinq-cent", imageUrl: "assets/images/compter/500.png",audioMap: {"Fè'éfè'é":"audios/compter/500-cinq_cent.mp3","Douala":""}),
  LectureModele(text: "six-cent", imageUrl: "assets/images/compter/600.png",audioMap: {"Fè'éfè'é":"audios/compter/600-six_cent.mp3","Douala":""}),
  LectureModele(text: "sept-cent", imageUrl: "assets/images/compter/700.png",audioMap: {"Fè'éfè'é":"audios/compter/700-sept_cent.mp3","Douala":""}),
  LectureModele(text: "huit-cent", imageUrl: "assets/images/compter/800.png",audioMap: {"Fè'éfè'é":"audios/compter/800-huit_cent.mp3","Douala":""}),
  LectureModele(text: "neuf-cent", imageUrl: "assets/images/compter/900.png",audioMap: {"Fè'éfè'é":"audios/compter/900-neuf_cent.mp3","Douala":""}),
  LectureModele(text: "mille", imageUrl: "assets/images/compter/1000.png",audioMap: {"Fè'éfè'é":"audios/compter/1000-mille.mp3","Douala":""}),
],
listeLectureFruit = [
  LectureModele(text: "ananas", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/ananas.mp3","Douala":""}),
  LectureModele(text: "avocat", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/avocat.mp3","Douala":""}),
  LectureModele(text: "banane", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/banane.mp3","Douala":""}),
  LectureModele(text: "citron", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/citron.mp3","Douala":""}),
  LectureModele(text: "corossol", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/corossol.mp3","Douala":""}),
  LectureModele(text: "goyave", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/goyave.mp3","Douala":""}),
  LectureModele(text: "mangue", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/mangue.mp3","Douala":""}),
  LectureModele(text: "noix_de_coco", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/noix_de_coco.mp3","Douala":""}),
  LectureModele(text: "orange", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/orange.mp3","Douala":""}),
  LectureModele(text: "palmiste", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/palmiste.mp3","Douala":""}),
  LectureModele(text: "papaye", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/papaye.mp3","Douala":""}),

  LectureModele(text: "pomme_de_terre", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/pomme_de_terre.mp3","Douala":""}),
  LectureModele(text: "prune", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/prune.mp3","Douala":""}),
  LectureModele(text: "tomate", imageUrl: "",audioMap: {"Fè'éfè'é":"audios/fruits/tomate.mp3","Douala":""}),
  
],
listeLectureAnimaux = [
  LectureModele(text: "abeille", imageUrl: "assets/images/animaux/l_abeille.png",audioMap: {"Fè'éfè'é":"audios/animaux/l_abeille.mp3","Douala":""}),
  LectureModele(text: "chevre", imageUrl: "assets/images/animaux/la_chevre.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_chevre.mp3","Douala":""}),
  LectureModele(text: "aigle", imageUrl: "assets/images/animaux/l_aigle.png",audioMap: {"Fè'éfè'é":"audios/animaux/l_aigle.mp3","Douala":""}),
  LectureModele(text: "mouche", imageUrl: "assets/images/animaux/la_mouche.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_mouche.mp3","Douala":""}),
  LectureModele(text: "antilope", imageUrl: "assets/images/animaux/l_antilope.png",audioMap: {"Fè'éfè'é":"audios/animaux/l_antilope.mp3","Douala":""}),
  LectureModele(text: "panthere", imageUrl: "assets/images/animaux/la_panthere.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_panthere.mp3","Douala":""}),
  LectureModele(text: "perdrix", imageUrl: "assets/images/animaux/la_perdrix.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_perdrix.mp3","Douala":""}),
  LectureModele(text: "poule", imageUrl: "assets/images/animaux/la_poule.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_poule.mp3","Douala":""}),
  LectureModele(text: "queue", imageUrl: "assets/images/animaux/la_queue.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_queue.mp3","Douala":""}),
  LectureModele(text: "souris", imageUrl: "assets/images/animaux/la_souris.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_souris.mp3","Douala":""}),
  LectureModele(text: "tortue", imageUrl: "assets/images/animaux/la_tortue.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_tortue.mp3","Douala":""}),
  LectureModele(text: "vache", imageUrl: "assets/images/animaux/la_vache.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_vache.mp3","Douala":""}),
  LectureModele(text: "vipere", imageUrl: "assets/images/animaux/la_vipere.png",audioMap: {"Fè'éfè'é":"audios/animaux/la_vipere.mp3","Douala":""}),
  LectureModele(text: "belier", imageUrl: "assets/images/animaux/le_belier.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_belier.mp3","Douala":""}),

  LectureModele(text: "boeuf", imageUrl: "assets/images/animaux/le_boeuf.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_boeuf.mp3","Douala":""}),
  LectureModele(text: "buffle", imageUrl: "assets/images/animaux/le_buffle.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_buffle.mp3","Douala":""}),
  LectureModele(text: "cameleon", imageUrl: "assets/images/animaux/le_cameleon.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_cameleon.mp3","Douala":""}),
  LectureModele(text: "cancrelat", imageUrl: "assets/images/animaux/le_cancrelat.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_cancrelat.mp3","Douala":""}),
  LectureModele(text: "cheval", imageUrl: "assets/images/animaux/le_cheval.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_cheval.mp3","Douala":""}),
  LectureModele(text: "chien", imageUrl: "assets/images/animaux/le_chien.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_chien.mp3","Douala":""}),
  LectureModele(text: "coq", imageUrl: "assets/images/animaux/le_coq.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_coq.mp3","Douala":""}),
  LectureModele(text: "hibou", imageUrl: "assets/images/animaux/le_hibou.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_hibou.mp3","Douala":""}),
  LectureModele(text: "elephant", imageUrl: "assets/images/animaux/l_elephant.png",audioMap: {"Fè'éfè'é":"audios/animaux/l_elephant.mp3","Douala":""}),
  LectureModele(text: "lievre", imageUrl: "assets/images/animaux/le_lievre.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_lievre.mp3","Douala":""}),
  LectureModele(text: "lion", imageUrl: "assets/images/animaux/le_lion.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_lion.mp3","Douala":""}),
  LectureModele(text: "loup", imageUrl: "assets/images/animaux/le_loup.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_loup.mp3","Douala":""}),
  LectureModele(text: "mouton", imageUrl: "assets/images/animaux/le_mouton.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_mouton.mp3","Douala":""}),
  LectureModele(text: "papillon", imageUrl: "assets/images/animaux/le_papillon.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_papillon.mp3","Douala":""}),
  
  LectureModele(text: "poussin", imageUrl: "assets/images/animaux/le_poussin.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_poussin.mp3","Douala":""}),
  LectureModele(text: "rat", imageUrl: "assets/images/animaux/le_rat.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_rat.mp3","Douala":""}),
  LectureModele(text: "renard", imageUrl: "assets/images/animaux/le_renard.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_renard.mp3","Douala":""}),
  LectureModele(text: "serpent", imageUrl: "assets/images/animaux/le_serpent.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_serpent.mp3","Douala":""}),
  LectureModele(text: "singe", imageUrl: "assets/images/animaux/le_singe.png",audioMap: {"Fè'éfè'é":"audios/animaux/le_singe.mp3","Douala":""}),
  LectureModele(text: "hippopotame", imageUrl: "assets/images/animaux/l_hippopotame.png",audioMap: {"Fè'éfè'é":"audios/animaux/l_hippopotame.mp3","Douala":""}),
  LectureModele(text: "oiseau", imageUrl: "assets/images/animaux/l_oiseau.png",audioMap: {"Fè'éfè'é":"audios/animaux/l_oiseau.mp3","Douala":""}),
  LectureModele(text: "oeuf", imageUrl: "assets/images/animaux/oeuf.png",audioMap: {"Fè'éfè'é":"audios/animaux/oeuf.mp3","Douala":""}),
]
;