
import '../../../../constants/app_constants.dart';
import '../../lecture/lecture_modele.dart';

/*
0 -> "Fè'éfè'é"
1 -> "Douala"
2 -> "Bangangté"
3 -> "Yambassa"
4 ->  "Étón"
*/
int indexNufi = 0,indexDouala = 1, indexBangante = 2, indexYambassa = 3, indexEton = 4;
var listeLecturePresentation = [
  LectureModele(text: "1_presentation", imageUrl: "${imageUrlBasePresentation}salut_lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}1-salut_mon_frere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "2_presentation", imageUrl: "${imageUrlBasePresentation}salut_ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}2-je_te_salut_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "3_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}3-comment_tu_t_appelle_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "4_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}4-je_m_appelle_ndisie_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "5_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}5-et_toi_comment_tu_t_appelle_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "6_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}6-je_m_appelle_lonam_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "7_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}7-tu_as_un_joli_nom_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "8_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}8-ou_habites_tu_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "9_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}9-j_habite_a_bana_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "10_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}10-et_toi_ou_habites_tu_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "11_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}11-j_habite_a_babone_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "12_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}12-tu_es_d_ou_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),

  LectureModele(text: "13_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}13-je_suis_originaire_de_nkwenzhi_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "14_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}14-et_toi_tu_es_originaire_d_ou_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "15_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}15-je_suis_originaire_de_baboutche_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "16_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}16-quel_age_as_tu_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "17_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}17-j_ai_sept_ans_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "18_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}18-et_toi_quel_age_as_tu_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "19_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}19-j_ai_neuf_ans_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "20_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}20-quel_est_le_nom_de_ton_pere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "21_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}21-mon_pere_s_appelle_fienkak_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "22_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}22-et_toi_comment_s_appelle_ton_pere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "23_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}23-le_nom_de_mon_pere_est_jiande_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "24_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}24-quel_est_le_nom_de_ta_mere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),

LectureModele(text: "25_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}25-le_nom_de_ma_mere_est_kena_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "26_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}26-enchante_de_faire_ta_connaissance_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "27_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}27-le_plaisir_est_le_mien_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "28_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}28-a_la_prochaine_ma_soeur_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "29_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}29-a_la_prochaine_s_il_plait_a_dieu_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "30_presentation", imageUrl: "${imageUrlBasePresentation}Lonam.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}30-au_revoir_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),
  LectureModele(text: "31_presentation", imageUrl: "${imageUrlBasePresentation}Ndiesie.png",audioMap: {languePrisEnCharge[indexNufi]:"${audioUrlBasePresentation}31-au_revoir_mon_frere_nufi.ogg",languePrisEnCharge[indexDouala]:"",languePrisEnCharge[indexBangante]:"",languePrisEnCharge[indexYambassa]:"",languePrisEnCharge[indexEton]:""}),

  ];
