var i18Fr = {
  "1": "maman",
  "2": "Ma mère",
  "3": "Oui",
  "4": "Non",
  "5": "Pourquoi",
  "6": "Parce-que",
  "7": "Le sein",
  "8": "Les seins",
  "9": "Le lait",
  "10": "La tête",
  "11": "Les oreilles",
  "12": "Les yeux",
  "13": "La main",
  "14": "La bouche",
  "15": "Les dents",
  "16": "La langue",
  "17": "Le pied",
  "18": "Le ventre",
  "19": "C'est qui ?",
  "20": "C'est moi !",
  "21": "C'est quoi ?",
  
  "22": "Rien",
  "23": "voir",
  "24": "l'habit",
  "25": "l'eau",
  "26": "boire de l'eau",
  "27": "le chien",
  "28": "viens",
  "29": "le serpent",
  "30": "donne",
  "31": "donne-moi",
  "32": "quitte de là !",
  "33": "ris",
  "34": "pleure",
  "35": "tais-toi",
  "36": "Papa",
  "37": "Mon père",
  "38": "Mon frère",
  "39": "Ma soeur",
  "40": "Un garçon",
  "41": "Un homme",
  "42": "Une femme",
  "43": "Salue-moi",
  "44": "Manger",
  "45": "Le verre, le gobelet",
  "46": "Les chaussures",
  "47": "Le chapeau",
  "48": "tiens",
  "49": "Lance",
  "50": "Jette",
  "51": "Applaudis",
  "52": "Pousse",
  "53": "Tire, ramène vers toi",
  "54": "Viens prendre",
  "61": "Dors",
  "62": "S'il te plaît",
  "63": "Ferme",
  "64": "Ouvre la porte",
  "65": "Ferme la porte",
  "66": "Assois-toi",
  "67": "Descends",
  "68": "Monte",
  "69": "Tu entends",
  "70": "Je",
  "71": "Tu",
  "72": "Il, elle",
  "73": "Nous",
  "74": "Vous",
  "75": "Ils, elles",
  "76": "J'ai oublié",
  "77": "Pour qui",
  "78": "C'est pour qui",
  
  "nom_projet":"Reenamuna",
  "premier_mot":"Mes premiers mots",
  "dialogue":"Dialogues",
  "compter":"Compter",
  "animaux":"Animaux",
  "fruit":"Fruits",
  "mois":"Mois de l'année",
   "zero":"Zéro",
  "un":"Un",
  "deux":"Deux",
  "trois":"Trois",
  "quatre":"Quatre",
  "cinq":"Cinq",
  "six":"Six",
  "sept":"Sept",
  "huit":"Huit",
  "neuf":"Neuf",
  "dix":"Dix",
  "onze":"Onze",
  "douze":"Douze",
  "treize":"Treize",
  "quatoze":"Quatorze",
  "quinze":"Quinze",
  "seize":"Seize",
  "dix-sept":"Dix-sept",
  "dix-huit":"Dix-huit",
  "dix-neuf":"Dix-neuf",
  "vingt":"Vingt",
  "trente":"Trente",
  "quarante":"Quarante",
  "cinquante":"Cinquante",
  "soixante":"Soixante",
  "soixante-dix":"Soixante-dix",
  "quatre-vingt":"Quatre-vingts",
  "quatre-vingt-dix":"Quatre-vingt-dix",
  "cent":"Cent",
  "deux-cent":"Deux cents",
  "trois-cent":"Trois cents",
  "quatre-cent":"Quatre cents",
  "cinq-cent":"Cinq cents",
  "six-cent":"Six cents",
  "sept-cent":"Sept cents",
  "huit-cent":"Huit cents",
  "neuf-cent":"Neuf cents",
  "mille":"Mille",

  "langue":"Français",
  "presentation_dialog":"Présentation",
  "salutation_dialog":"Salutation",
  "min_atteint":"Vous êtes au plus petit nombre",
  "max_atteint":"Vous êtes au plus grand nombre",
  "unable_to_load":"Erreur système : Impossible de charger cette image",
  "empty_translation":"Aucune traduction pour ce mot",

  "abeille":"L'abeille",
  "chevre":"La chèvre",
  "aigle":"L'aigle",
  "mouche":"La mouche",
  "antilope":"L'antilope",
  "panthere":"La panthère",
  "perdrix":"La perdrix",
  "poule":"La poule",
  "queue":"La queue",
  "souris":"La souris",
  "tortue":"La tortue",
  "vache":"La vache",
  "vipere":"La vipère",
  "belier":"Le belier",
  "buffle":"Le buffle",
  "boeuf":"Le boeuf",
  "cameleon":"Le caméléon",
  "cancrelat":"Le cancrelat",
  "cheval":"Le cheval",
  "chien":"Le chien",
  "coq":"Le coq",
  "hibou":"Le hibou",
  "elephant":"L'éléphant",
  "lievre":"Le lièvre",
  "lion":"Le lion",
  "loup":"Le loup",
  "mouton":"Le mouton",
  "papillon":"Le papillon",
  "poussin":"Le poussin",
  "rat":"Le rat",
  "renard":"Le renard",
  "serpent":"Le serpent",
  "singe":"Le singe",
  "hippopotame":"L'hippopotame",
  "oeuf":"L'oeuf",
  "oiseau":"L'oiseau",
  "avocat":"L'avocat",
  "ananas":"L'ananas",
  "banane":"La banane",
  "citron":"Le citron",
  "corossol":"Le corossol",
  "goyave":"La goyave",
  "mangue":"La mangue",
  "noix_de_coco":"La noix de coco",
  "orange":"L'orange",
  "palmiste":"Le palmiste",
  "papaye":"La papaye",
  "pomme_de_terre":"La pomme de terre",
  "prune":"La prune",
  "tomate":"La tomate",
  
  "corne":"La corne",
  "peau":"La peau",
  "poil":"Le poil",
  "ecaille":"Une écaille",
  "fourmi":"Une fourmie",
  "girafe":"Une girafe",
  "patte":"Une patte",
  "plume":"Une plume",
  "poisson":"Un poisson",
  "zebre":"Un zèbre",
  "clique_ici":"Cliquer ici",
  
  //salutation
  "2_lonam":"Bonjour ma grande soeur Mbouani",
  "3_mbouani":"Bonjour mon petit frère Lonam",
  "4_mbouani":"Comment ça va ?",
  "5_lonam":"Ça va bien merci",
  "6_lonam":"Salut papa",
  "7_papa":"Salut mon enfant comment ça va ?",
  "8_lonam":"Ça va bien papa",
  "9_lonam":"Et toi alors ?",
  "10_papa":"Ça va bien mon enfant",
  "11_mbouani":"Bonsoir maman",
  "12_maman":"Bonsoir mon enfant comment ça va ?",
  "13_mbouani":"Ça va bien maman. Et toi?",
  "14_maman":"Ça va bien mon enfant, merci",
  "15_mbouani":"Bonne nuit mon frère Lonam",
  "16_lonam":"Bonne nuit ma soeur Mbouani",
  "17_enfants":"Bonne nuit papa, bonne nuit maman",
  "18_parents":"Nous vous remercions",
  "19_parents":"Bonne nuit à vous mes enfants, demain",
  
  // presentation
  "1_presentation":"Salut ma soeur",
  "2_presentation":"Je te salut",
  "3_presentation":"Comment t'appelles-tu ?",
  "4_presentation":"Je m'appelle Ndisie",
  "5_presentation":"Et toi, comment t'appelles-tu ?",
  "6_presentation":"Je m'appelle Lonam",
  "7_presentation":"Tu as un joli nom",
  "8_presentation":"Où habitues-tu ?",
  "9_presentation":"J'habite à Bana",
  "10_presentation":"Et toi, où habites-tu ?",
  "11_presentation":"J'habite à Banoné",
  "12_presentation":"D'où es tu originaire ?",
  "13_presentation":"Je suis originaire de Nkwè'nzhi",
  "14_presentation":"Et toi, d'où es tu originaire ?",
  "15_presentation":"Je suis originaire de Baboutcheu",
  "16_presentation":"Quel âge as-tu ?",
  "17_presentation":"J'ai 7 ans",
  "18_presentation":"Et toi, quel âge as-tu ?",
  "19_presentation":"J'ai 9 ans",
  "20_presentation":"Quel est le nom de ton père ?",
  "21_presentation":"Mon père s'appelle Fienkak",
  "22_presentation":"Et toi, comment s'appelle ton père ?",
  "23_presentation":"Le nom de mon père est Jiande",
  "24_presentation":"Quel est le nom de ta mère ?",
  "25_presentation":"Le nom de ma mère est Kena",
  "26_presentation":"Enchanté de faire ta connaissance",
  "27_presentation":"Le plaisir est le mien",
  "28_presentation":"À la prochaine ma soeur",
  "29_presentation":"À la prochaine s'il plaît à Dieu",
  "30_presentation":"Au-revoir",
  "31_presentation":"Au-revoir mon frère",
  
  // mois de l'annee
  "janvier":"Janvier",
  "fevrier":"Février",
  "mars":"Mars",
  "avril":"Avril",
  "mai":"Mai",
  "juin":"Juin",
  "juillet":"Juillet",
  "aout":"Août",
  "septembre":"Septembre",
  "octobre":"Octobre",
  "novembre":"Novembre",
  "decembre":"Décembre",

};

