var i18Fr = {
  "1": "maman",
  "2": "Ma mère",
  "3": "oui",
  "4": "non",
  "5": "pourquoi",
  "6": "parce que",
  "7": "le sein",
  "8": "les seins",
  "9": "le lait",
  "10": "la tête",
  "11": "les oreilles",
  "12": "les yeux",
  "13": "la main",
  "14": "la bouche",
  "15": "les dents",
  "16": "la langue",
  "17": "le pied",
  "18": "le ventre",
  "19": "c'est qui ?",
  "20": "c'est moi !",
  "21": "c'est quoi ?",
  "22": "Rien",
  "23": "voir",
  "24": "l'habit",
  "25": "l'eau",
  "26": "boire de l'eau",
  "27": "le chien",
  "28": "viens",
  "29": "le serpent",
  "30": "donne",
  "31": "donne-moi",
  "32": "quitte de là !",
  "33": "ris",
  "34": "pleure",
  "35": "tais-toi",
  "36": "Papa",
  "37": "Mon père",
  "38": "Mon frère",
  "39": "Ma soeur",
  "40": "Un garçon",
  "41": "Un homme",
  "42": "Une femme",
  "43": "Salue-moi",
  "44": "Manger",
  "45": "Le verre, le gobelet",
  "46": "Les chaussures",
  "47": "Le chapeau",
  "48": "tiens",
  "49": "Lance",
  "50": "Jette",
  "51": "Applaudis",
  "52": "Pousse",
  "53": "Tire, ramène vers toi",
  "54": "Viens prendre",
  "55": "Zéro",
  "56": "Un",
  "57": "Deux",
  "58": "Trois",
  "59": "Quatre",
  "60": "Cinq",
  "61": "Dors",
  "62": "S'il te plaît",
  "63": "Ferme",
  "64": "Ouvre la porte",
  "65": "Ferme la porte",
  "66": "Assois-toi",
  "67": "Descends",
  "68": "Monte",
  "69": "Tu entends",
  "70": "Je",
  "71": "Tu",
  "72": "Il, elle",
  "73": "Nous",
  "74": "Vous",
  "75": "Ils, elles",
  "76": "J'ai oublié",
  "77": "Pour qui",
  "78": "C'est pour qui",
  
  "nom_projet":"Reenamuna",
  "premier_mot":"Mes premiers mots",
  "dialogue":"Dialogues",
  "compter":"Nombre",
  "animaux":"Animaux",
  "fruit":"Fruits",
  "mois":"Mois de l'année",
   "zero":"Zéro",
  "un":"Un",
  "deux":"Deux",
  "trois":"Trois",
  "quatre":"Quatre",
  "cinq":"Cinq",
  "six":"Six",
  "sept":"Sept",
  "huit":"Huit",
  "neuf":"Neuf",
  "dix":"Dix",
  "onze":"Onze",
  "douze":"Douze",
  "treize":"Treize",
  "quatoze":"Quatorze",
  "quinze":"Quinze",
  "seize":"Seize",
  "dix-sept":"Dix-sept",
  "dix-huit":"Dix-huit",
  "dix-neuf":"Dix-neuf",
  "vingt":"Vingt",
  "trente":"Trente",
  "quarante":"Quarante",
  "cinquante":"Cinquante",
  "soixante":"Soixante",
  "soixante-dix":"Soixante-dix",
  "quatre-vingt":"Quatre-vingts",
  "quatre-vingt-dix":"Quatre-vingt-dix",
  "cent":"Cent",
  "deux-cent":"Deux cents",
  "trois-cent":"Trois cents",
  "quatre-cent":"Quatre cents",
  "cinq-cent":"Cinq cents",
  "six-cent":"Six cents",
  "sept-cent":"Sept cents",
  "huit-cent":"Huit cents",
  "neuf-cent":"Neuf cents",
  "mille":"Mille",

  "langue":"Français",
  "presentation_dialog":"Présentation",
  "salutation_dialog":"Salutation",
  "min_atteint":"Vous êtes au plus petit nombre",
  "max_atteint":"Vous êtes au plus grand nombre",
  "unable_to_load":"Erreur système : Impossible de charger cette image",
  "empty_translation":"Aucune traduction pour ce mot"
 
};

