var i18En = {
  "1": "Mom",
  "2": "My mother",
  "3": "Yes",
  "4": "No",
  "5": "Why",
  "6": "Because",
  "7": "Breast",
  "8": "Breasts",
  "9": "Milk",
  "10": "Head",
  "11": "Ears",
  "12": "Eyes",
  "13": "Hand",
  "14": "Mouth",
  "15": "Teeth",
  "16": "Tongue",
  "17": "Foot",
  "18": "Belly",
  "19": "Who is it?",
  "20": "It's me!",
  "21": "What is it?",
  "22": "Nothing",
  "23": "See",
  "24": "Clothing",
  "25": "Water",
  "26": "Drink water",
  "27": "Dog",
  "28": "Come",
  "29": "Snake",
  "30": "Give",
  "31": "Give me",
  "32": "Get out of there!",
  "33": "Laugh",
  "34": "Cry",
  "35": "Be quiet",
  "36": "Dad",
  "37": "My father",
  "38": "My brother",
  "39": "My sister",
  "40": "A boy",
  "41": "A man",
  "42": "A woman",
  "43": "Greet me",
  "44": "Eat",
  "45": "Glass, cup",
  "46": "Shoes",
  "47": "Hat",
  "48": "Hold",
  "49": "Throw",
  "50": "Throw",
  "51": "Applaud",
  "52": "Push",
  "53": "Pull, bring it to you",
  "54": "Come and get it",
  "61": "Sleep",
  "62": "Please",
  "63": "Close",
  "64": "Open the door",
  "65": "Close the door",
  "66": "Sit down",
  "67": "Get down",
  "68": "Go up",
  "69": "Do you hear",
  "70": "I",
  "71": "You",
  "72": "He, she",
  "73": "We",
  "74": "You (plural)",
  "75": "They",
  "76": "I forgot",
  "77": "For whom",
  "78": "Whose is it",

  "nom_projet":"Reenamuna",
  "premier_mot":"My First Words",
  "dialogue":"Dialogues",
  "compter":"Counting",
  "animaux":"Animals",
  "fruit":"Fruits",
  "mois":"Months of the year",
   "zero":"Zero",
  "un":"One",
  "deux":"Two",
  "trois":"Three",
  "quatre":"Four",
  "cinq":"Five",
  "six":"Six",
  "sept":"Seven",
  "huit":"Eight",
  "neuf":"Nine",
  "dix":"Ten",
  "onze":"Eleven",
  "douze":"Twelve",
  "treize":"Thirteen",
  "quatoze":"Fourteen",
  "quinze":"Fifteen",
  "seize":"Sixteen",
  "dix-sept":"Seventeen",
  "dix-huit":"Eighteen",
  "dix-neuf":"Nineteen",
  "vingt":"Twenty",
  "trente":"Thirty",
  "quarante":"Forty",
  "cinquante":"Fifty",
  "soixante":"Sixty",
  "soixante-dix":"Seventy",
  "quatre-vingt":"Eighty",
  "quatre-vingt-dix":"Ninety",
  "cent":"One Hundred",
  "deux-cent":"Two Hundred",
  "trois-cent":"Three Hundred",
  "quatre-cent":"Four Hundred",
  "cinq-cent":"Five Hundred",
  "six-cent":"Six Hundred",
  "sept-cent":"Seven Hundred",
  "huit-cent":"Height Hundred",
  "neuf-cent":"Nine Hundred",
  "mille":"One Thousand",

  "langue":"English",
  "presentation_dialog":"Presentation",
  "salutation_dialog":"Greeting",
  "min_atteint":"You are at the smallest number",
  "max_atteint":"You are at the biggest number",
  "unable_to_load":"System Error : Unable to load this image",
  "empty_translation":"No translation for this word",
  "abeille": "Bee",
"chevre": "Goat",
"aigle": "Eagle",
"mouche": "Fly",
"antilope": "Antelope",
"panthere": "Panther",
"perdrix": "Partridge",
"poule": "Hen",
"queue": "Tail",
"souris": "Mouse",
"tortue": "Turtle",
"vache": "Cow",
"vipere": "Viper",
"belier": "Ram",
"buffle": "Buffalo",
"boeuf": "Ox",
"cameleon": "Chameleon",
"cancrelat": "Cockroach",
"cheval": "Horse",
"chien": "Dog",
"coq": "Rooster",
"hibou": "Owl",
"elephant": "Elephant",
"lievre": "Hare",
"lion": "Lion",
"loup": "Wolf",
"mouton": "Sheep",
"papillon": "Butterfly",
"poussin": "Chick",
"rat": "Rat",
"renard": "Fox",
"serpent": "Snake",
"singe": "Monkey",
"hippopotame": "Hippopotamus",
"oeuf": "Egg",
"oiseau": "Bird",
"avocat": "Avocado",
"ananas": "Pineapple",
"banane": "Banana",
"citron": "Lemon",
"corossol": "Soursop",
"goyave": "Guava",
"mangue": "Mango",
"noix_de_coco": "Coconut",
"orange": "Orange",
"palmiste": "Palm kernel",
"papaye": "Papaya",
"pomme_de_terre": "Potato",
"prune": "Plum",
"tomate": "Tomato",

"corne":"Horn",
  "peau":"Skin",
  "poil":"Hair",
  "ecaille":"Scale",
  "fourmi":"Ant",
  "girafe":"Giraffe",
  "patte":"Paw",
  "plume":"Feather",
  "poisson":"Fish",
  "zebre":"Zebra",
  "clique_ici":"Click here",
  
  "2_lonam": "Hello, my big sister Mbouani",
"3_mbouani": "Hello, my little brother Lonam",
"4_mbouani": "How are you?",
"5_lonam": "I'm fine, thank you",
"6_lonam": "Hi dad",
"7_papa": "Hi, my child, how are you?",
"8_lonam": "I'm fine, dad",
"9_lonam": "And you?",
"10_papa": "I'm fine, my child",
"11_mbouani": "Good evening, mom",
"12_maman": "Good evening, my child, how are you?",
"13_mbouani": "I'm fine, mom. And you?",
"14_maman": "I'm fine, my child, thank you",
"15_mbouani": "Good night, my brother Lonam",
"16_lonam": "Good night, my sister Mbouani",
"17_enfants": "Good night, dad, good night, mom",
"18_parents": "Thank you",
"19_parents": "Good night to you, my children, until tomorrow",
  
  "1_presentation": "Hi, my sister",
  "2_presentation": "I greet you",
  "3_presentation": "What is your name?",
  "4_presentation": "My name is Ndisie",
  "5_presentation": "And you, what is your name?",
  "6_presentation": "My name is Lonam",
  "7_presentation": "You have a nice name",
  "8_presentation": "Where do you live?",
  "9_presentation": "I live in Bana",
  "10_presentation": "And you, where do you live?",
  "11_presentation": "I live in Banoné",
  "12_presentation": "Where are you from?",
  "13_presentation": "I am from Nkwè'nzhi",
  "14_presentation": "And you, where are you from?",
  "15_presentation": "I am from Baboutcheu",
  "16_presentation": "How old are you?",
  "17_presentation": "I am 7 years old",
  "18_presentation": "And you, how old are you?",
  "19_presentation": "I am 9 years old",
  "20_presentation": "What is your father's name?",
  "21_presentation": "My father's name is Fienkak",
  "22_presentation": "And you, what is your father's name?",
  "23_presentation": "My father's name is Jiande",
  "24_presentation": "What is your mother's name?",
  "25_presentation": "My mother's name is Kena",
  "26_presentation": "Nice to meet you",
  "27_presentation": "The pleasure is mine",
  "28_presentation": "Until next time, my sister",
  "29_presentation": "Until next time, God willing",
  "30_presentation": "Goodbye",
  "31_presentation": "Goodbye, my brother",
  
  // Months of the year
  "janvier": "January",
  "fevrier": "February",
  "mars": "March",
  "avril": "April",
  "mai": "May",
  "juin": "June",
  "juillet": "July",
  "aout": "August",
  "septembre": "September",
  "octobre": "October",
  "novembre": "November",
  "decembre": "December"

  };
  
