var i18En = {
  "1": "mom",
  "2": "My mother",
  "3": "yes",
  "4": "no",
  "5": "why",
  "6": "because",
  "7": "breast",
  "8": "breasts",
  "9": "milk",
  "10": "head",
  "11": "ears",
  "12": "eyes",
  "13": "hand",
  "14": "mouth",
  "15": "teeth",
  "16": "tongue",
  "17": "foot",
  "18": "belly",
  "19": "who is it?",
  "20": "it's me!",
  "21": "what is it?",
  "22": "Nothing",
  "23": "see",
  "24": "clothing",
  "25": "water",
  "26": "drink water",
  "27": "dog",
  "28": "come",
  "29": "snake",
  "30": "give",
  "31": "give me",
  "32": "get out of there!",
  "33": "laugh",
  "34": "cry",
  "35": "be quiet",
  "36": "Dad",
  "37": "My father",
  "38": "My brother",
  "39": "My sister",
  "40": "A boy",
  "41": "A man",
  "42": "A woman",
  "43": "Greet me",
  "44": "Eat",
  "45": "Glass, cup",
  "46": "Shoes",
  "47": "Hat",
  "48": "hold",
  "49": "Throw",
  "50": "Throw",
  "51": "Applaud",
  "52": "Push",
  "53": "Pull, bring it to you",
  "54": "Come and get it",
  "55": "Zero",
  "56": "One",
  "57": "Two",
  "58": "Three",
  "59": "Four",
  "60": "Five",
  "61": "Sleep",
  "62": "Please",
  "63": "Close",
  "64": "Open the door",
  "65": "Close the door",
  "66": "Sit down",
  "67": "Get down",
  "68": "Go up",
  "69": "Do you hear",
  "70": "I",
  "71": "You",
  "72": "He, she",
  "73": "We",
  "74": "You (plural)",
  "75": "They",
  "76": "I forgot",
  "77": "For whom",
  "78": "Whose is it",

  "nom_projet":"Reenamuna",
  "premier_mot":"My First Words",
  "dialogue":"Dialogues",
  "compter":"Counting",
  "animaux":"Animals",
  "fruit":"Fruits",
  "mois":"Months of the year",
   "zero":"Zero",
  "un":"One",
  "deux":"Two",
  "trois":"Three",
  "quatre":"Four",
  "cinq":"Five",
  "six":"Six",
  "sept":"Seven",
  "huit":"Eight",
  "neuf":"Nine",
  "dix":"Ten",
  "onze":"Eleven",
  "douze":"Twelve",
  "treize":"Thirteen",
  "quatoze":"Fourteen",
  "quinze":"Fifteen",
  "seize":"Sixteen",
  "dix-sept":"Seventeen",
  "dix-huit":"Eighteen",
  "dix-neuf":"Nineteen",
  "vingt":"Twenty",
  "trente":"Thirty",
  "quarante":"Forty",
  "cinquante":"Fifty",
  "soixante":"Sixty",
  "soixante-dix":"Seventy",
  "quatre-vingt":"Eighty",
  "quatre-vingt-dix":"Ninety",
  "cent":"One Hundred",
  "deux-cent":"Two Hundred",
  "trois-cent":"Three Hundred",
  "quatre-cent":"Four Hundred",
  "cinq-cent":"Five Hundred",
  "six-cent":"Six Hundred",
  "sept-cent":"Seven Hundred",
  "huit-cent":"Height Hundred",
  "neuf-cent":"Nine Hundred",
  "mille":"One Thousand",

  "langue":"English",
  "presentation_dialog":"Presentation",
  "salutation_dialog":"Greeting",
  "min_atteint":"You are at the smallest number",
  "max_atteint":"You are at the biggest number",
  "unable_to_load":"System Error : Unable to load this image",
  "empty_translation":"No translation for this word",
  "abeille": "The bee",
"chevre": "The goat",
"aigle": "The eagle",
"mouche": "The fly",
"antilope": "The antelope",
"panthere": "The panther",
"perdrix": "The partridge",
"poule": "The hen",
"queue": "The tail",
"souris": "The mouse",
"tortue": "The turtle",
"vache": "The cow",
"vipere": "The viper",
"belier": "The ram",
"buffle": "The buffalo",
"boeuf": "The ox",
"cameleon": "The chameleon",
"cancrelat": "The cockroach",
"cheval": "The horse",
"chien": "The dog",
"coq": "The rooster",
"hibou": "The owl",
"elephant": "The elephant",
"lievre": "The hare",
"lion": "The lion",
"loup": "The wolf",
"mouton": "The sheep",
"papillon": "The butterfly",
"poussin": "The chick",
"rat": "The rat",
"renard": "The fox",
"serpent": "The snake",
"singe": "The monkey",
"hippopotame": "The hippopotamus",
"oeuf": "The egg",
"oiseau": "The bird",
"avocat": "The avocado",
"ananas": "The pineapple",
"banane": "The banana",
"citron": "The lemon",
"corossol": "The soursop",
"goyave": "The guava",
"mangue": "The mango",
"noix_de_coco": "The coconut",
"orange": "The orange",
"palmiste": "The palm kernel",
"papaye": "The papaya",
"pomme_de_terre": "The potato",
"prune": "The plum",
"tomate": "The tomato",

"corne":"Horn",
  "peau":"Skin",
  "poil":"Hair",
  "ecaille":"Scale",
  "fourmi":"Ant",
  "girafe":"Giraffe",
  "patte":"Paw",
  "plume":"Feather",
  "poisson":"Fish",
  "zebre":"Zebra"
  };
